### ISSUE TITLE
支持预渲染

### ISSUE THREAD

**Issue by xueran** [Ralltiir/ralltiir#19]
视频页面打开时，为了做到速度方面的体验（在页面打开时，就能立即播放视频和展现内容）需要提前预渲染视频页面。
端版本：基于localstorage 通信，在searchframe里面做预渲染
H5版本：在当前页面做预渲染

**Comment by oott123** [comment]
对实例化 service 而言，框架提供以下能力，可支持预渲染等类似逻辑：

* services 增加接口，使得外部可以提前创建、缓存并获取 service 实例。
* service 本身提供接口，使得外部可以调用其对应的处理函数，以支持预渲染或预取或其它任何逻辑。
* dispatch 逻辑不变；对相同 url，继续通过上述缓存中获取的 service 实例来正常处理生命周期。

需要考虑的问题：

* 是否需要 service 提供 API，在即将进入缓存 / 即将从缓存中取出复用时，检查实例是否可进入缓存/被取出？这将提供 service 干预缓存管理的能力，能精确控制不需要/无法被缓存的实例。
* services 模块本身无法从 url 获取 pathPattern ，故无法知晓应当创建何种实例；当前这个功能是 router 实现的，是否应当 router 暴露接口以实现该功能？

**Comment by oott123** [comment]
对于 Native 能力而言，这里会有额外的问题：

* 如何跨 js 传递对象？
    因为在 native 多 webview 场景，创建的 service 实例是在另外的 webview 创建的；此时，框架不大可能返回 service 对象用于操作。
    或许可以返回一个被代理的 service 实例，自动管理进行 RPC ？

**Comment by tayqassqan** [comment]
外部调用时候不应该直接使用Service的API吧？RT对Service的管理和Router的操作解耦，这里是否已经支持？

**Comment by tayqassqan** [comment]
另一个问题是对于被渲染页面，在渲染层级执行上需要如何区分执行，在对应的标签标记和配置上，也需要看一下方案。

**Comment by oott123** [comment]
@tayqassqan 

> 外部调用时候不应该直接使用Service的API吧？

其实没太多所谓。如果预渲染需要做到框架里面，理论上是需要框架提供 API 由框架调用的。
但事实上这类机制太过细节，并不适合在框架里面做，因而框架负责创建、管理 service 是较为合理的，得到实例后可以做任何事情。

> RT对Service的管理和Router的操作解耦，这里是否已经支持？

本来也从未解耦，注册时需要两边都注册。现在的问题是，根据 path 找 service 的代码写到了 router 里。把它弄出来单独做一个函数即可。

> 另外，对于被渲染页，渲染层级的定义和声明也需要明确一下。

这些属于 service 内部的问题了。

就 MIP 而言，当前的方案并未分级。

**Comment by oott123** [comment]
预渲染跨 webview 的部分的解决方法：

框架不关心跨 webview 与否。如果需要跨 webview 预渲染，主文档需要自己想办法通知子文档，使其在子文档（如搜索框架）中做预渲染；这个机制与跨 webview 跳转类似，主文档通知子文档跳转，而自己不做任何事情。

**Comment by oott123** [comment]
看了目前的代码，ralltiir 在其中需要提供的功能应该已经基本实现了，只需要业务方调用即可。
